-- Current schema (generated by Alembic)
-- To view the complete schema, run: alembic current
-- For full history: alembic history

-- ⚠️ NOTE: This is a snapshot of the current schema.
-- The source of truth is in migrations/ (Alembic).
-- To apply migrations: alembic upgrade head

CREATE TABLE public.categories_elettrodomestico (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200)
);

CREATE TABLE public.devices (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    average_watts INTEGER NOT NULL,
    standby_watts INTEGER NOT NULL DEFAULT 0,
    category_id INTEGER NOT NULL REFERENCES public.categories_elettrodomestico(id)
);